/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package modul12_1302223118_gui;

/**
 *
 * @author rakha
 */
public class EditDialog extends javax.swing.JDialog {

    private Mahasiswa selectedMahasiswa;

    /**
     * Creates new form EditDialog
     */
    public EditDialog(java.awt.Frame parent, boolean modal, Mahasiswa mhs) {
        super(parent, modal);
        initComponents();
        selectedMahasiswa = mhs;
        NIMTextField.setText(selectedMahasiswa.getNim());
        namaTextField.setText(selectedMahasiswa.getNama());
        String prodi = selectedMahasiswa.getProdi();
        if (prodi.equals("IF")) {
            IFRadioButton.setSelected(true);
        } else if (prodi.equals("SE")) {
            SERadioButton.setSelected(true);
        } else if (prodi.equals("IT")) {
            ITRadioButton.setSelected(true);
        } else if (prodi.equals("DS")) {
            DSRadioButton.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        NIMTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        IFRadioButton = new javax.swing.JRadioButton();
        SERadioButton = new javax.swing.JRadioButton();
        ITRadioButton = new javax.swing.JRadioButton();
        DSRadioButton = new javax.swing.JRadioButton();
        simpanButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("NIM :");

        jLabel8.setText("Nama :");

        jLabel9.setText("Prodi :");

        buttonGroup1.add(IFRadioButton);
        IFRadioButton.setText("IF");

        buttonGroup1.add(SERadioButton);
        SERadioButton.setText("SE");

        buttonGroup1.add(ITRadioButton);
        ITRadioButton.setText("IT");

        buttonGroup1.add(DSRadioButton);
        DSRadioButton.setText("DS");

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("© Rakha - 1302223118");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IFRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(SERadioButton))
                            .addComponent(namaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(NIMTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ITRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(DSRadioButton))
                            .addComponent(simpanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NIMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IFRadioButton)
                        .addComponent(SERadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ITRadioButton)
                    .addComponent(DSRadioButton))
                .addGap(18, 18, 18)
                .addComponent(simpanButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        String prodi = "";
        String NIM = NIMTextField.getText();
        String nama = namaTextField.getText();
        if (IFRadioButton.isSelected()) {
            prodi = "IF";
        } else if (SERadioButton.isSelected()) {
            prodi = "SE";
        } else if (ITRadioButton.isSelected()) {
            prodi = "IT";
        } else if (DSRadioButton.isSelected()) {
            prodi = "DS";
        }

        if (!NIM.isEmpty() && !nama.isEmpty() && !prodi.isEmpty()) {
            Mahasiswa mhs = new Mahasiswa(NIM, nama, prodi);
            JDBC.updateMahasiswa(mhs, selectedMahasiswa.getNim());
            this.setVisible(false);
        } else {
            // Tampilkan pesan error jika data tidak lengkap
            javax.swing.JOptionPane.showMessageDialog(this, "Data tidak lengkap!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_simpanButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DSRadioButton;
    private javax.swing.JRadioButton IFRadioButton;
    private javax.swing.JRadioButton ITRadioButton;
    private javax.swing.JTextField NIMTextField;
    private javax.swing.JRadioButton SERadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JButton simpanButton;
    // End of variables declaration//GEN-END:variables
}
